[package]
name = 'ciflyr'
publish = false
version = '0.1.1'
edition = '2021'
rust-version = '1.65'

[lib]
crate-type = [ 'staticlib' ]
name = 'ciflyr'

[dependencies]
cifly = "0.1.3"
extendr-api = "0.8"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
