[package]
name = 'ciflyr'
publish = false
version = '0.1.0'
edition = '2021'
rust-version = '1.65'

[lib]
crate-type = [ 'staticlib' ]
name = 'ciflyr'

[dependencies]
cifly = "0.1.0"
extendr-api = '*'
