[package]
name = 'ciflyR'
publish = false
version = '0.1.0'
edition = '2021'
rust-version = '1.65'

[lib]
crate-type = [ 'staticlib' ]
name = 'ciflyR'

[dependencies]
cifly = { path = "../../../cifly" }
extendr-api = '*'
