[project]
name = "ciflypy-examples"
version = "0.1.0"
description = ""
authors = [
{name = "Marcel Wienöbst",email = "marcel.wienoebst@gmx.de"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ciflypy>=0.1.1",
]

[dependency-groups]
dev = [
    "pytest>=8.3.5",
]
